/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/*
 * STM32F103RBT6 note:
 * PC8 is a digital GPIO pin, not an ADC input. A potentiometer or voltage
 * divider must be connected to an ADC-capable pin such as PA0 (ADC1_IN0).
 *
 * Wiring used by this example:
 *   Pot end 1 -> 3V3
 *   Pot end 2 -> GND
 *   Pot wiper -> PA0 / ADC1_IN0
 *
 * USART2 TX is on PA2. On Nucleo boards this is typically connected to the
 * ST-LINK virtual COM port. Open it at 9600-8-N-1.
 */

#define SYSTEM_CORE_CLOCK_HZ 8000000UL
#define USART2_BAUD         9600UL
#define ADC_MAX_COUNTS      4095UL
#define VDDA_MV             3300UL
#define POT_TOTAL_OHMS      5000UL
#define REPORT_INTERVAL_MS  500UL

#define PERIPH_BASE         0x40000000UL
#define APB1PERIPH_BASE     PERIPH_BASE
#define APB2PERIPH_BASE     (PERIPH_BASE + 0x00010000UL)
#define AHBPERIPH_BASE      (PERIPH_BASE + 0x00020000UL)

#define GPIOA_BASE          (APB2PERIPH_BASE + 0x00000800UL)
#define RCC_BASE            (AHBPERIPH_BASE + 0x00001000UL)
#define ADC1_BASE           (APB2PERIPH_BASE + 0x00002400UL)
#define USART2_BASE         (APB1PERIPH_BASE + 0x00004400UL)

#define SYST_CSR            (*(volatile uint32_t *)0xE000E010UL)
#define SYST_RVR            (*(volatile uint32_t *)0xE000E014UL)
#define SYST_CVR            (*(volatile uint32_t *)0xE000E018UL)

typedef struct
{
    volatile uint32_t CRL;
    volatile uint32_t CRH;
    volatile uint32_t IDR;
    volatile uint32_t ODR;
    volatile uint32_t BSRR;
    volatile uint32_t BRR;
    volatile uint32_t LCKR;
} GPIO_TypeDef;

typedef struct
{
    volatile uint32_t CR;
    volatile uint32_t CFGR;
    volatile uint32_t CIR;
    volatile uint32_t APB2RSTR;
    volatile uint32_t APB1RSTR;
    volatile uint32_t AHBENR;
    volatile uint32_t APB2ENR;
    volatile uint32_t APB1ENR;
    volatile uint32_t BDCR;
    volatile uint32_t CSR;
} RCC_TypeDef;

typedef struct
{
    volatile uint32_t SR;
    volatile uint32_t CR1;
    volatile uint32_t CR2;
    volatile uint32_t SMPR1;
    volatile uint32_t SMPR2;
    volatile uint32_t JOFR1;
    volatile uint32_t JOFR2;
    volatile uint32_t JOFR3;
    volatile uint32_t JOFR4;
    volatile uint32_t HTR;
    volatile uint32_t LTR;
    volatile uint32_t SQR1;
    volatile uint32_t SQR2;
    volatile uint32_t SQR3;
    volatile uint32_t JSQR;
    volatile uint32_t JDR1;
    volatile uint32_t JDR2;
    volatile uint32_t JDR3;
    volatile uint32_t JDR4;
    volatile uint32_t DR;
} ADC_TypeDef;

typedef struct
{
    volatile uint32_t SR;
    volatile uint32_t DR;
    volatile uint32_t BRR;
    volatile uint32_t CR1;
    volatile uint32_t CR2;
    volatile uint32_t CR3;
    volatile uint32_t GTPR;
} USART_TypeDef;

#define GPIOA               ((GPIO_TypeDef *)GPIOA_BASE)
#define RCC                 ((RCC_TypeDef *)RCC_BASE)
#define ADC1                ((ADC_TypeDef *)ADC1_BASE)
#define USART2              ((USART_TypeDef *)USART2_BASE)

#define RCC_CFGR_ADCPRE_Pos 14U
#define RCC_APB2ENR_AFIOEN  (1UL << 0)
#define RCC_APB2ENR_IOPAEN  (1UL << 2)
#define RCC_APB2ENR_ADC1EN  (1UL << 9)
#define RCC_APB1ENR_USART2EN (1UL << 17)

#define USART_SR_TXE        (1UL << 7)
#define USART_CR1_TE        (1UL << 3)
#define USART_CR1_UE        (1UL << 13)

#define ADC_SR_EOC          (1UL << 1)
#define ADC_CR2_ADON        (1UL << 0)
#define ADC_CR2_CAL         (1UL << 2)
#define ADC_CR2_RSTCAL      (1UL << 3)
#define ADC_CR2_EXTSEL_Pos  17U
#define ADC_CR2_EXTSEL_SWSTART (7UL << ADC_CR2_EXTSEL_Pos)
#define ADC_CR2_EXTTRIG     (1UL << 20)
#define ADC_CR2_SWSTART     (1UL << 22)

#define SYST_CSR_ENABLE     (1UL << 0)
#define SYST_CSR_TICKINT    (1UL << 1)
#define SYST_CSR_CLKSOURCE  (1UL << 2)

typedef enum
{
    ADC_INIT_IDLE = 0,
    ADC_INIT_STABILIZE,
    ADC_INIT_RESET_CALIBRATION,
    ADC_INIT_CALIBRATE,
    ADC_INIT_READY
} AdcInitState;

static volatile uint32_t g_ms_ticks;
static AdcInitState g_adc_init_state = ADC_INIT_IDLE;
static uint32_t g_adc_power_on_ms;

void SystemInit(void)
{
    /* Keep the reset clock tree: HSI 8 MHz as SYSCLK. */
}

void SysTick_Handler(void)
{
    g_ms_ticks++;
}

static uint32_t millis(void)
{
    return g_ms_ticks;
}

static uint8_t interval_elapsed(uint32_t *last_ms, uint32_t interval_ms)
{
    const uint32_t now = millis();

    if ((uint32_t)(now - *last_ms) < interval_ms)
    {
        return 0U;
    }

    *last_ms = now;
    return 1U;
}

static void systick_init(void)
{
    SYST_RVR = (SYSTEM_CORE_CLOCK_HZ / 1000UL) - 1UL;
    SYST_CVR = 0UL;
    SYST_CSR = SYST_CSR_CLKSOURCE | SYST_CSR_TICKINT | SYST_CSR_ENABLE;
}

static void peripheral_clock_init(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_AFIOEN | RCC_APB2ENR_IOPAEN | RCC_APB2ENR_ADC1EN;
    RCC->APB1ENR |= RCC_APB1ENR_USART2EN;

    /* ADC clock = PCLK2 / 6 = 1.33 MHz when SYSCLK/PCLK2 are 8 MHz. */
    RCC->CFGR = (RCC->CFGR & ~(3UL << RCC_CFGR_ADCPRE_Pos)) |
                (2UL << RCC_CFGR_ADCPRE_Pos);

    (void)RCC->APB2ENR;
    (void)RCC->APB1ENR;
}

static void gpio_init(void)
{
    /* PA0 = analog input for ADC1_IN0. */
    GPIOA->CRL &= ~(0xFUL << 0);

    /* PA2 = USART2_TX, alternate-function push-pull, 2 MHz. */
    GPIOA->CRL = (GPIOA->CRL & ~(0xFUL << 8)) | (0xAUL << 8);
}

static void usart2_init(void)
{
    USART2->CR1 = 0UL;
    USART2->CR2 = 0UL;
    USART2->CR3 = 0UL;
    USART2->BRR = (SYSTEM_CORE_CLOCK_HZ + (USART2_BAUD / 2UL)) / USART2_BAUD;
    USART2->CR1 = USART_CR1_TE | USART_CR1_UE;
}

static void uart_write_char(char ch)
{
    if (ch == '\n')
    {
        uart_write_char('\r');
    }

    while ((USART2->SR & USART_SR_TXE) == 0UL)
    {
        /* Wait for TX data register empty. */
    }

    USART2->DR = (uint32_t)(uint8_t)ch;
}

int __io_putchar(int ch)
{
    uart_write_char((char)ch);
    return ch;
}

static void uart_write_string(const char *text)
{
    while (*text != '\0')
    {
        uart_write_char(*text++);
    }
}

static void uart_write_u32(uint32_t value)
{
    char buffer[10];
    uint32_t index = 0;

    if (value == 0UL)
    {
        uart_write_char('0');
        return;
    }

    while (value > 0UL)
    {
        buffer[index++] = (char)('0' + (value % 10UL));
        value /= 10UL;
    }

    while (index > 0UL)
    {
        uart_write_char(buffer[--index]);
    }
}

static void adc1_init_start(void)
{
    ADC1->CR1 = 0UL;
    ADC1->CR2 = 0UL;

    /* Channel 0 sample time = 239.5 ADC cycles for stable high-impedance reads. */
    ADC1->SMPR2 = (ADC1->SMPR2 & ~(7UL << 0)) | (7UL << 0);
    ADC1->SQR1 = 0UL;
    ADC1->SQR3 = 0UL;
    ADC1->CR2 = (ADC1->CR2 & ~(7UL << ADC_CR2_EXTSEL_Pos)) |
                ADC_CR2_EXTSEL_SWSTART |
                ADC_CR2_EXTTRIG;

    ADC1->CR2 |= ADC_CR2_ADON;
    g_adc_power_on_ms = millis();
    g_adc_init_state = ADC_INIT_STABILIZE;
}

static uint8_t adc1_init_task(void)
{
    switch (g_adc_init_state)
    {
    case ADC_INIT_STABILIZE:
        if ((uint32_t)(millis() - g_adc_power_on_ms) < 1UL)
        {
            return 0U;
        }

        ADC1->CR2 |= ADC_CR2_RSTCAL;
        g_adc_init_state = ADC_INIT_RESET_CALIBRATION;
        return 0U;

    case ADC_INIT_RESET_CALIBRATION:
        if ((ADC1->CR2 & ADC_CR2_RSTCAL) != 0UL)
        {
            return 0U;
        }

        ADC1->CR2 |= ADC_CR2_CAL;
        g_adc_init_state = ADC_INIT_CALIBRATE;
        return 0U;

    case ADC_INIT_CALIBRATE:
        if ((ADC1->CR2 & ADC_CR2_CAL) != 0UL)
        {
            return 0U;
        }

        g_adc_init_state = ADC_INIT_READY;
        return 1U;

    case ADC_INIT_READY:
        return 1U;

    case ADC_INIT_IDLE:
    default:
        return 0U;
    }
}

static uint16_t adc1_read_channel0(void)
{
    ADC1->SQR3 = 0UL;
    ADC1->SR = 0UL;
    ADC1->CR2 |= ADC_CR2_SWSTART;

    while ((ADC1->SR & ADC_SR_EOC) == 0UL)
    {
        /* Wait for conversion complete. */
    }

    return (uint16_t)(ADC1->DR & 0x0FFFUL);
}

static uint16_t adc1_read_average(void)
{
    uint32_t sum = 0UL;

    for (uint32_t i = 0UL; i < 16UL; i++)
    {
        sum += adc1_read_channel0();
    }

    return (uint16_t)((sum + 8UL) / 16UL);
}

int main(void)
{
    uint32_t last_report_ms = 0UL;
    uint8_t banner_printed = 0U;

    systick_init();
    peripheral_clock_init();
    gpio_init();
    usart2_init();
    adc1_init_start();

    for (;;)
    {
        if (adc1_init_task() == 0U)
        {
            continue;
        }

        if (banner_printed == 0U)
        {
            uart_write_string("\nSTM32F103 potentiometer monitor\n");
            uart_write_string("ADC input: PA0 / ADC1_IN0. PC8 is not an ADC pin on STM32F103RB.\n");
            uart_write_string("Wiring: 3V3 -- pot end, GND -- pot end, wiper -- PA0.\n\n");
            last_report_ms = millis() - REPORT_INTERVAL_MS;
            banner_printed = 1U;
        }

        if (interval_elapsed(&last_report_ms, REPORT_INTERVAL_MS) == 0U)
        {
            continue;
        }

        const uint32_t adc_raw = adc1_read_average();
        const uint32_t millivolts = ((adc_raw * VDDA_MV) + (ADC_MAX_COUNTS / 2UL)) /
                                    ADC_MAX_COUNTS;
        const uint32_t r_wiper_to_gnd = ((adc_raw * POT_TOTAL_OHMS) +
                                         (ADC_MAX_COUNTS / 2UL)) /
                                        ADC_MAX_COUNTS;
        const uint32_t r_wiper_to_3v3 = POT_TOTAL_OHMS - r_wiper_to_gnd;

        uart_write_string("ADC=");
        uart_write_u32(adc_raw);
        uart_write_string("  V=");
        uart_write_u32(millivolts);
        uart_write_string("mV  Rgnd=");
        uart_write_u32(r_wiper_to_gnd);
        uart_write_string("ohm  R3v3=");
        uart_write_u32(r_wiper_to_3v3);
        uart_write_string("ohm\n");
    }
}
