/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if 0
#define PERIPH_BASE        (0x40000000UL)
#define APB2PERIPH_BASE    (PERIPH_BASE + 0x00010000UL)
#define AHBPERIPH_BASE     (PERIPH_BASE + 0x00018000UL)

#define GPIOA_BASE         (APB2PERIPH_BASE + 0x00000800UL)
#define GPIOC_BASE         (APB2PERIPH_BASE + 0x00001000UL)
#define RCC_BASE           (AHBPERIPH_BASE + 0x00009000UL)

#define RCC_APB2ENR        (*(volatile uint32_t *)(RCC_BASE + 0x18UL))

#define GPIOA_CRL          (*(volatile uint32_t *)(GPIOA_BASE + 0x00UL))
#define GPIOA_BSRR         (*(volatile uint32_t *)(GPIOA_BASE + 0x10UL))

#define GPIOC_CRH          (*(volatile uint32_t *)(GPIOC_BASE + 0x04UL))
#define GPIOC_IDR          (*(volatile uint32_t *)(GPIOC_BASE + 0x08UL))
#define GPIOC_ODR          (*(volatile uint32_t *)(GPIOC_BASE + 0x0CUL))

#define RCC_APB2ENR_IOPAEN (1UL << 2)
#define RCC_APB2ENR_IOPCEN (1UL << 4)

#define LED_PIN            (5UL)  /* NUCLEO-F103RB LD2: PA5 */
#define BUTTON_PIN         (8UL)  /* External switch input: PC8 */

static void gpio_init(void);
static int button_is_pressed(void);
static void led_on(void);
static void led_off(void);
static void delay_cycles(volatile uint32_t cycles);
static int delay_or_button(uint32_t chunks);

void SystemInit(void)
{
}

int main(void)
{
    gpio_init();

    for (;;) {
        if (button_is_pressed()) {
            led_off();
            continue;
        }

        led_on();
        if (delay_or_button(80U)) {
            led_off();
            continue;
        }

        led_off();
        delay_or_button(80U);
    }
}

static void gpio_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPCEN;

    /* PA5 output, push-pull, 2 MHz. */
    GPIOA_CRL &= ~(0xFUL << (LED_PIN * 4UL));
    GPIOA_CRL |=  (0x2UL << (LED_PIN * 4UL));

    /* PC8 input with pull-down. In STM32F1, ODR=0 selects pull-down. */
    GPIOC_CRH &= ~(0xFUL << ((BUTTON_PIN - 8UL) * 4UL));
    GPIOC_CRH |=  (0x8UL << ((BUTTON_PIN - 8UL) * 4UL));
    GPIOC_ODR &= ~(1UL << BUTTON_PIN);

    led_off();
}

static int button_is_pressed(void)
{
    return (GPIOC_IDR & (1UL << BUTTON_PIN)) != 0U;
}

static void led_on(void)
{
    GPIOA_BSRR = (1UL << LED_PIN);
}

static void led_off(void)
{
    GPIOA_BSRR = (1UL << (LED_PIN + 16UL));
}

static void delay_cycles(volatile uint32_t cycles)
{
    while (cycles-- > 0U) {
    }
}

static int delay_or_button(uint32_t chunks)
{
    while (chunks-- > 0U) {
        if (button_is_pressed()) {
            return 1;
        }
        delay_cycles(10000U);
    }

    return 0;
}
#endif

#if 0
/* PA5/LD2 + user button pattern code */
#define PERIPH_BASE                (0x40000000UL)
#define APB2PERIPH_BASE            (PERIPH_BASE + 0x00010000UL)
#define AHBPERIPH_BASE             (PERIPH_BASE + 0x00018000UL)

#define GPIOA_BASE                 (APB2PERIPH_BASE + 0x00000800UL)
#define GPIOC_BASE                 (APB2PERIPH_BASE + 0x00001000UL)
#define RCC_BASE                   (AHBPERIPH_BASE + 0x00009000UL)

#define RCC_APB2ENR                (*(volatile uint32_t *)(RCC_BASE + 0x18UL))

#define GPIOA_CRL                  (*(volatile uint32_t *)(GPIOA_BASE + 0x00UL))
#define GPIOA_BSRR                 (*(volatile uint32_t *)(GPIOA_BASE + 0x10UL))

#define GPIOC_CRH                  (*(volatile uint32_t *)(GPIOC_BASE + 0x04UL))
#define GPIOC_IDR                  (*(volatile uint32_t *)(GPIOC_BASE + 0x08UL))
#define GPIOC_ODR                  (*(volatile uint32_t *)(GPIOC_BASE + 0x0CUL))

#define SYST_CSR                   (*(volatile uint32_t *)0xE000E010UL)
#define SYST_RVR                   (*(volatile uint32_t *)0xE000E014UL)
#define SYST_CVR                   (*(volatile uint32_t *)0xE000E018UL)

#define RCC_APB2ENR_IOPAEN         (1UL << 2)
#define RCC_APB2ENR_IOPCEN         (1UL << 4)

#define SYST_CSR_ENABLE            (1UL << 0)
#define SYST_CSR_CLKSOURCE         (1UL << 2)
#define SYST_CSR_COUNTFLAG         (1UL << 16)

#define GPIO_CONFIG_MASK           (0xFUL)
#define GPIO_MODE_OUTPUT_2MHZ_PP   (0x2UL)
#define GPIO_MODE_INPUT_PULL       (0x8UL)
#define GPIO_LOW_PIN_SHIFT(pin)    ((pin) * 4UL)
#define GPIO_HIGH_PIN_SHIFT(pin)   (((pin) - 8UL) * 4UL)
#define GPIO_PIN(pin)              (1UL << (pin))
#define GPIO_BSRR_SET(pin)         GPIO_PIN(pin)
#define GPIO_BSRR_RESET(pin)       GPIO_PIN((pin) + 16UL)

#define LD2_PIN                    (5UL)   /* NUCLEO-F103RB LD2: PA5 */
#define USER_BUTTON_PIN            (13UL)  /* NUCLEO-F103RB B1: PC13, active low */
#define SYSTEM_CORE_CLOCK_HZ       (8000000UL)
#define SYSTICK_1MS_RELOAD         ((SYSTEM_CORE_CLOCK_HZ / 1000UL) - 1UL)
#define DEBOUNCE_DELAY_MS          (20UL)
#define BLINK_INTERVAL_MS          (500UL)

static void gpio_init(void);
static void ld2_init(void);
static void user_button_init(void);
static void systick_init(void);
static int user_button_press_started(void);
static int user_button_is_pressed(void);
static void ld2_set(int enabled);
static void run_odd_press_pattern(void);
static void run_even_press_pattern(void);
static int delay_while_button_pressed(uint32_t ms);
static void delay_ms(uint32_t ms);

void SystemInit(void)
{
}

int main(void)
{
    uint32_t press_count = 0U;

    gpio_init();
    systick_init();
    ld2_set(0);

    for (;;) {
        if (!user_button_press_started()) {
            ld2_set(0);
            continue;
        }

        press_count++;

        if ((press_count & 1UL) != 0U) {
            run_odd_press_pattern();
        } else {
            run_even_press_pattern();
        }

        ld2_set(0);
        delay_ms(DEBOUNCE_DELAY_MS);
    }
}

static void gpio_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPCEN;

    ld2_init();
    user_button_init();
}

static void ld2_init(void)
{
    const uint32_t shift = GPIO_LOW_PIN_SHIFT(LD2_PIN);

    GPIOA_CRL &= ~(GPIO_CONFIG_MASK << shift);
    GPIOA_CRL |=  (GPIO_MODE_OUTPUT_2MHZ_PP << shift);
}

static void user_button_init(void)
{
    const uint32_t shift = GPIO_HIGH_PIN_SHIFT(USER_BUTTON_PIN);

    /* PC13 input with pull-up. B1 pulls PC13 low when pressed. */
    GPIOC_CRH &= ~(GPIO_CONFIG_MASK << shift);
    GPIOC_CRH |=  (GPIO_MODE_INPUT_PULL << shift);
    GPIOC_ODR |=  GPIO_PIN(USER_BUTTON_PIN);
}

static void systick_init(void)
{
    SYST_RVR = SYSTICK_1MS_RELOAD;
    SYST_CVR = 0U;
    SYST_CSR = SYST_CSR_CLKSOURCE | SYST_CSR_ENABLE;
}

static int user_button_press_started(void)
{
    if (!user_button_is_pressed()) {
        return 0;
    }

    delay_ms(DEBOUNCE_DELAY_MS);
    return user_button_is_pressed();
}

static int user_button_is_pressed(void)
{
    return (GPIOC_IDR & GPIO_PIN(USER_BUTTON_PIN)) == 0U;
}

static void ld2_set(int enabled)
{
    if (enabled) {
        GPIOA_BSRR = GPIO_BSRR_SET(LD2_PIN);
    } else {
        GPIOA_BSRR = GPIO_BSRR_RESET(LD2_PIN);
    }
}

static void run_odd_press_pattern(void)
{
    int led_enabled = 1;

    while (user_button_is_pressed()) {
        ld2_set(led_enabled);

        if (!delay_while_button_pressed(BLINK_INTERVAL_MS)) {
            break;
        }

        led_enabled = !led_enabled;
    }
}

static void run_even_press_pattern(void)
{
    ld2_set(1);

    while (user_button_is_pressed()) {
        delay_ms(1U);
    }
}

static int delay_while_button_pressed(uint32_t ms)
{
    while (ms-- > 0U) {
        delay_ms(1U);

        if (!user_button_is_pressed()) {
            return 0;
        }
    }

    return 1;
}

static void delay_ms(uint32_t ms)
{
    while (ms-- > 0U) {
        SYST_CVR = 0U;
        while ((SYST_CSR & SYST_CSR_COUNTFLAG) == 0U) {
        }
    }
}
#endif

#define PERIPH_BASE                (0x40000000UL)
#define APB2PERIPH_BASE            (PERIPH_BASE + 0x00010000UL)
#define AHBPERIPH_BASE             (PERIPH_BASE + 0x00018000UL)

#define GPIOC_BASE                 (APB2PERIPH_BASE + 0x00001000UL)
#define RCC_BASE                   (AHBPERIPH_BASE + 0x00009000UL)

#define RCC_APB2ENR                (*(volatile uint32_t *)(RCC_BASE + 0x18UL))

#define GPIOC_CRH                  (*(volatile uint32_t *)(GPIOC_BASE + 0x04UL))
#define GPIOC_BSRR                 (*(volatile uint32_t *)(GPIOC_BASE + 0x10UL))

#define SYST_CSR                   (*(volatile uint32_t *)0xE000E010UL)
#define SYST_RVR                   (*(volatile uint32_t *)0xE000E014UL)
#define SYST_CVR                   (*(volatile uint32_t *)0xE000E018UL)

#define RCC_APB2ENR_IOPCEN         (1UL << 4)

#define SYST_CSR_ENABLE            (1UL << 0)
#define SYST_CSR_CLKSOURCE         (1UL << 2)
#define SYST_CSR_COUNTFLAG         (1UL << 16)

#define GPIO_CONFIG_MASK           (0xFUL)
#define GPIO_MODE_OUTPUT_2MHZ_PP   (0x2UL)
#define GPIO_HIGH_PIN_SHIFT(pin)   (((pin) - 8UL) * 4UL)
#define GPIO_PIN(pin)              (1UL << (pin))
#define GPIO_BSRR_SET(pin)         GPIO_PIN(pin)
#define GPIO_BSRR_RESET(pin)       GPIO_PIN((pin) + 16UL)

#define PC8_LED_PIN                (8UL)
#define SYSTEM_CORE_CLOCK_HZ       (8000000UL)
#define SYSTICK_1MS_RELOAD         ((SYSTEM_CORE_CLOCK_HZ / 1000UL) - 1UL)
#define PHASE_DURATION_MS          (10000UL)
#define BLINK_1X_INTERVAL_MS       (300UL)
#define BLINK_2X_INTERVAL_MS       (150UL)
#define BLINK_3X_INTERVAL_MS       (100UL)

static void gpio_init(void);
static void pc8_led_init(void);
static void systick_init(void);
static void pc8_led_on(void);
static void pc8_led_off(void);
static void run_blink_phase(uint32_t interval_ms);
static void delay_ms(uint32_t ms);

void SystemInit(void)
{
}

int main(void)
{
    gpio_init();
    systick_init();

    for (;;) {
        run_blink_phase(BLINK_3X_INTERVAL_MS);
        run_blink_phase(BLINK_2X_INTERVAL_MS);
        run_blink_phase(BLINK_1X_INTERVAL_MS);
    }
}

static void gpio_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPCEN;
    pc8_led_init();
}

static void pc8_led_init(void)
{
    const uint32_t shift = GPIO_HIGH_PIN_SHIFT(PC8_LED_PIN);

    GPIOC_CRH &= ~(GPIO_CONFIG_MASK << shift);
    GPIOC_CRH |=  (GPIO_MODE_OUTPUT_2MHZ_PP << shift);
}

static void systick_init(void)
{
    SYST_RVR = SYSTICK_1MS_RELOAD;
    SYST_CVR = 0U;
    SYST_CSR = SYST_CSR_CLKSOURCE | SYST_CSR_ENABLE;
}

static void pc8_led_off(void)
{
    GPIOC_BSRR = GPIO_BSRR_RESET(PC8_LED_PIN);
}

static void pc8_led_on(void)
{
    GPIOC_BSRR = GPIO_BSRR_SET(PC8_LED_PIN);
}

static void run_blink_phase(uint32_t interval_ms)
{
    uint32_t elapsed_ms = 0U;
    int led_enabled = 0;

    while (elapsed_ms < PHASE_DURATION_MS) {
        if (led_enabled) {
            pc8_led_on();
        } else {
            pc8_led_off();
        }

        delay_ms(interval_ms);
        elapsed_ms += interval_ms;
        led_enabled = !led_enabled;
    }
}

static void delay_ms(uint32_t ms)
{
    while (ms-- > 0U) {
        SYST_CVR = 0U;
        while ((SYST_CSR & SYST_CSR_COUNTFLAG) == 0U) {
        }
    }
}
