/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_APB2ENR   (*(volatile uint32_t *)0x40021018u)
#define GPIOB_CRL     (*(volatile uint32_t *)0x40010C00u)
#define GPIOB_ODR     (*(volatile uint32_t *)0x40010C0Cu)
#define GPIOC_CRL     (*(volatile uint32_t *)0x40011000u)
#define GPIOC_ODR     (*(volatile uint32_t *)0x4001100Cu)

#define RCC_APB2ENR_IOPBEN  (1u << 3)
#define RCC_APB2ENR_IOPCEN  (1u << 4)
#define LED_D10_PIN         6u
#define LED_D10_MASK        (1u << LED_D10_PIN)
#define LED_D9_PIN          7u
#define LED_D9_MASK         (1u << LED_D9_PIN)

void SystemInit(void)
{
    /* Use the reset clock setup: HSI 8 MHz. */
}

static void delay_ms(uint32_t ms)
{
    while (ms-- > 0u) {
        for (volatile uint32_t i = 0u; i < 1000u; ++i) {
            __asm volatile ("nop");
        }
    }
}

int main(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN;

    /* Arduino D10 on NUCLEO-F103RB is PB6. Configure PB6 as 2 MHz push-pull output. */
    GPIOB_CRL = (GPIOB_CRL & ~(0xFu << 24)) | (0x2u << 24);

    /* Arduino D9 on NUCLEO-F103RB is PC7. Configure PC7 as 2 MHz push-pull output. */
    GPIOC_CRL = (GPIOC_CRL & ~(0xFu << 28)) | (0x2u << 28);

    for (;;) {
        GPIOB_ODR |= LED_D10_MASK;
        GPIOC_ODR &= ~LED_D9_MASK;
        delay_ms(500u);

        GPIOB_ODR &= ~LED_D10_MASK;
        GPIOC_ODR |= LED_D9_MASK;
        delay_ms(500u);
    }
}
