/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SYSCLK_HZ      8000000U
#define USART_BAUD     9600U
#define DEBOUNCE_MS    50U

#define PERIPH_BASE    0x40000000UL
#define APB1_BASE      PERIPH_BASE
#define APB2_BASE      (PERIPH_BASE + 0x00010000UL)
#define AHB_BASE       (PERIPH_BASE + 0x00018000UL)

#define USART2_BASE    (APB1_BASE + 0x00004400UL)
#define AFIO_BASE      (APB2_BASE + 0x00000000UL)
#define EXTI_BASE      (APB2_BASE + 0x00000400UL)
#define GPIOA_BASE     (APB2_BASE + 0x00000800UL)
#define GPIOC_BASE     (APB2_BASE + 0x00001000UL)
#define RCC_BASE       (AHB_BASE  + 0x00009000UL)

#define REG32(addr)    (*(volatile uint32_t *)(addr))

#define RCC_CR         REG32(RCC_BASE + 0x00UL)
#define RCC_CFGR       REG32(RCC_BASE + 0x04UL)
#define RCC_APB2ENR    REG32(RCC_BASE + 0x18UL)
#define RCC_APB1ENR    REG32(RCC_BASE + 0x1CUL)

#define GPIOA_CRL      REG32(GPIOA_BASE + 0x00UL)
#define GPIOA_BSRR     REG32(GPIOA_BASE + 0x10UL)
#define GPIOA_BRR      REG32(GPIOA_BASE + 0x14UL)

#define GPIOC_CRH      REG32(GPIOC_BASE + 0x04UL)
#define GPIOC_IDR      REG32(GPIOC_BASE + 0x08UL)
#define GPIOC_BSRR     REG32(GPIOC_BASE + 0x10UL)

#define AFIO_EXTICR4   REG32(AFIO_BASE + 0x14UL)

#define EXTI_IMR       REG32(EXTI_BASE + 0x00UL)
#define EXTI_RTSR      REG32(EXTI_BASE + 0x08UL)
#define EXTI_FTSR      REG32(EXTI_BASE + 0x0CUL)
#define EXTI_PR        REG32(EXTI_BASE + 0x14UL)

#define USART2_SR      REG32(USART2_BASE + 0x00UL)
#define USART2_DR      REG32(USART2_BASE + 0x04UL)
#define USART2_BRR     REG32(USART2_BASE + 0x08UL)
#define USART2_CR1     REG32(USART2_BASE + 0x0CUL)

#define SYST_CSR       REG32(0xE000E010UL)
#define SYST_RVR       REG32(0xE000E014UL)
#define SYST_CVR       REG32(0xE000E018UL)
#define NVIC_ISER1     REG32(0xE000E104UL)

#define RCC_CR_HSION        (1UL << 0)
#define RCC_CR_HSIRDY       (1UL << 1)
#define RCC_APB2ENR_AFIOEN  (1UL << 0)
#define RCC_APB2ENR_IOPAEN  (1UL << 2)
#define RCC_APB2ENR_IOPCEN  (1UL << 4)
#define RCC_APB1ENR_USART2EN (1UL << 17)

#define USART_SR_TXE        (1UL << 7)
#define USART_CR1_TE        (1UL << 3)
#define USART_CR1_UE        (1UL << 13)

#define LED_PIN             (1UL << 5)   /* LD2: PA5, active high */
#define BUTTON_PIN          (1UL << 13)  /* B1: PC13, active low */
#define EXTI15_10_IRQ_BIT   (1UL << 8)   /* IRQ 40 in NVIC ISER1 */

static volatile uint32_t system_ms;
static volatile uint32_t hi_events;
static uint32_t last_button_ms;
static uint8_t led_is_on;

void SystemInit(void)
{
    RCC_CR |= RCC_CR_HSION;
    while ((RCC_CR & RCC_CR_HSIRDY) == 0U) {
    }

    RCC_CFGR = 0U; /* HSI 8 MHz, AHB/APB prescalers all divide by 1. */
}

static void systick_init(void)
{
    SYST_RVR = (SYSCLK_HZ / 1000U) - 1U;
    SYST_CVR = 0U;
    SYST_CSR = 0x07U;
}

static void led_on(void)
{
    GPIOA_BSRR = LED_PIN;
    led_is_on = 1U;
}

static void led_off(void)
{
    GPIOA_BRR = LED_PIN;
    led_is_on = 0U;
}

static uint8_t button_is_pressed(void)
{
    return ((GPIOC_IDR & BUTTON_PIN) == 0U) ? 1U : 0U;
}

static void queue_hi_message(void)
{
    ++hi_events;
}

static void sync_led_with_button(uint8_t report_led_off)
{
    if (button_is_pressed() != 0U) {
        if (led_is_on != 0U) {
            led_off();
            if (report_led_off != 0U) {
                queue_hi_message();
            }
        }
    } else if (led_is_on == 0U) {
        led_on();
    }
}

static void usart2_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_AFIOEN | RCC_APB2ENR_IOPAEN;
    RCC_APB1ENR |= RCC_APB1ENR_USART2EN;

    /* PA2 = USART2_TX, alternate-function push-pull, 2 MHz. */
    GPIOA_CRL &= ~(0xFUL << 8);
    GPIOA_CRL |=  (0xAUL << 8);

    USART2_CR1 = 0U;
    USART2_BRR = (SYSCLK_HZ + (USART_BAUD / 2U)) / USART_BAUD;
    USART2_CR1 = USART_CR1_TE | USART_CR1_UE;
}

static void usart2_write_char(char ch)
{
    while ((USART2_SR & USART_SR_TXE) == 0U) {
    }

    USART2_DR = (uint32_t)(uint8_t)ch;
}

static void usart2_write_string(const char *text)
{
    while (*text != '\0') {
        usart2_write_char(*text);
        ++text;
    }
}

static void gpio_exti_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_AFIOEN | RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPCEN;

    /* PA5 = LD2 output, push-pull, 2 MHz. */
    GPIOA_CRL &= ~(0xFUL << 20);
    GPIOA_CRL |=  (0x2UL << 20);

    /* PC13 = B1 input with pull-up. Nucleo user button pulls the pin low. */
    GPIOC_CRH &= ~(0xFUL << 20);
    GPIOC_CRH |=  (0x8UL << 20);
    GPIOC_BSRR = BUTTON_PIN;

    led_on();
    last_button_ms = system_ms - DEBOUNCE_MS;
    sync_led_with_button(1U);

    /* Route EXTI13 to GPIOC and trigger on both press/release edges. */
    AFIO_EXTICR4 &= ~(0xFUL << 4);
    AFIO_EXTICR4 |=  (0x2UL << 4);

    EXTI_PR = BUTTON_PIN;
    EXTI_IMR |= BUTTON_PIN;
    EXTI_RTSR |= BUTTON_PIN;
    EXTI_FTSR |= BUTTON_PIN;

    NVIC_ISER1 = EXTI15_10_IRQ_BIT;
}

static uint8_t take_hi_event(void)
{
    uint8_t has_event = 0U;

    __asm volatile ("cpsid i" ::: "memory");
    if (hi_events != 0U) {
        --hi_events;
        has_event = 1U;
    }
    __asm volatile ("cpsie i" ::: "memory");

    return has_event;
}

void SysTick_Handler(void)
{
    ++system_ms;
}

void EXTI15_10_IRQHandler(void)
{
    if ((EXTI_PR & BUTTON_PIN) != 0U) {
        EXTI_PR = BUTTON_PIN;

        if ((system_ms - last_button_ms) >= DEBOUNCE_MS) {
            last_button_ms = system_ms;
            sync_led_with_button(1U);
        }
    }
}

int main(void)
{
    systick_init();
    usart2_init();
    gpio_exti_init();

    for (;;) {
        if (take_hi_event() != 0U) {
            usart2_write_string("HI\r\n");
        } else {
            __asm volatile ("wfi");
        }
    }
}
