/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/*
 * Bare-metal register access (no CMSIS/HAL in this project).
 * Board: NUCLEO-F103RB. Arduino pin mapping: D9 = PC7, D10 = PB6.
 *   D9  (PC7) -> TIM3_CH2, requires AFIO full remap of TIM3 (PC6..PC9)
 *   D10 (PB6) -> TIM4_CH1, default mapping, no remap needed
 */

#define RCC_BASE   0x40021000UL
#define AFIO_BASE  0x40010000UL
#define GPIOB_BASE 0x40010C00UL
#define GPIOC_BASE 0x40011000UL
#define TIM3_BASE  0x40000400UL
#define TIM4_BASE  0x40000800UL

#define RCC_APB2ENR (*(volatile uint32_t *)(RCC_BASE + 0x18))
#define RCC_APB1ENR (*(volatile uint32_t *)(RCC_BASE + 0x1C))

#define AFIO_MAPR   (*(volatile uint32_t *)(AFIO_BASE + 0x04))

#define GPIOB_CRL   (*(volatile uint32_t *)(GPIOB_BASE + 0x00))
#define GPIOC_CRL   (*(volatile uint32_t *)(GPIOC_BASE + 0x00))

#define TIM3_CR1    (*(volatile uint32_t *)(TIM3_BASE + 0x00))
#define TIM3_CCMR1  (*(volatile uint32_t *)(TIM3_BASE + 0x18))
#define TIM3_CCER   (*(volatile uint32_t *)(TIM3_BASE + 0x20))
#define TIM3_PSC    (*(volatile uint32_t *)(TIM3_BASE + 0x28))
#define TIM3_ARR    (*(volatile uint32_t *)(TIM3_BASE + 0x2C))
#define TIM3_CCR2   (*(volatile uint32_t *)(TIM3_BASE + 0x38))

#define TIM4_CR1    (*(volatile uint32_t *)(TIM4_BASE + 0x00))
#define TIM4_CCMR1  (*(volatile uint32_t *)(TIM4_BASE + 0x18))
#define TIM4_CCER   (*(volatile uint32_t *)(TIM4_BASE + 0x20))
#define TIM4_PSC    (*(volatile uint32_t *)(TIM4_BASE + 0x28))
#define TIM4_ARR    (*(volatile uint32_t *)(TIM4_BASE + 0x2C))
#define TIM4_CCR1   (*(volatile uint32_t *)(TIM4_BASE + 0x34))

/* Cortex-M3 core SysTick, fixed address regardless of vendor */
#define SYST_CSR    (*(volatile uint32_t *)(0xE000E010UL))
#define SYST_RVR    (*(volatile uint32_t *)(0xE000E014UL))
#define SYST_CVR    (*(volatile uint32_t *)(0xE000E018UL))

#define PWM_STEPS   100U /* ARR value: duty resolution 0..100 */

/* Reset already selects HSI 8 MHz as SYSCLK with no prescalers; keep it. */
void SystemInit(void)
{
}

static void systick_init_1ms(void)
{
    SYST_RVR = 8000UL - 1UL; /* 8 MHz / 8000 = 1 kHz tick */
    SYST_CVR = 0UL;
    SYST_CSR = (1UL << 0) | (1UL << 2); /* ENABLE, CLKSOURCE = AHB */
}

static void delay_ms(uint32_t ms)
{
    for (uint32_t i = 0; i < ms; i++) {
        while ((SYST_CSR & (1UL << 16)) == 0) {
            /* wait for COUNTFLAG */
        }
    }
}

static void gpio_pwm_init(void)
{
    RCC_APB2ENR |= (1UL << 0) | (1UL << 3) | (1UL << 4); /* AFIOEN, IOPBEN, IOPCEN */
    RCC_APB1ENR |= (1UL << 1) | (1UL << 2);               /* TIM3EN, TIM4EN */

    AFIO_MAPR = (AFIO_MAPR & ~(0x3UL << 10)) | (0x3UL << 10); /* TIM3 full remap -> CH2 on PC7 */

    /* PC7: MODE=11 (50MHz out), CNF=10 (AF push-pull) */
    GPIOC_CRL = (GPIOC_CRL & ~(0xFUL << 28)) | (0xBUL << 28);
    /* PB6: MODE=11 (50MHz out), CNF=10 (AF push-pull) */
    GPIOB_CRL = (GPIOB_CRL & ~(0xFUL << 24)) | (0xBUL << 24);
}

static void pwm_timers_init(void)
{
    /* Timer clock = 8 MHz (APB1 prescaler = 1). Prescale to 100 kHz, wrap at 100 -> 1 kHz PWM. */
    TIM3_PSC = 79;
    TIM3_ARR = PWM_STEPS - 1;
    TIM3_CCMR1 = (TIM3_CCMR1 & ~(0x7UL << 12)) | (0x6UL << 12) | (1UL << 11); /* OC2M=PWM1, OC2PE */
    TIM3_CCER |= (1UL << 4);  /* CC2E */
    TIM3_CCR2 = 0;
    TIM3_CR1 = (1UL << 7) | (1UL << 0); /* ARPE, CEN */

    TIM4_PSC = 79;
    TIM4_ARR = PWM_STEPS - 1;
    TIM4_CCMR1 = (TIM4_CCMR1 & ~(0x7UL << 4)) | (0x6UL << 4) | (1UL << 3); /* OC1M=PWM1, OC1PE */
    TIM4_CCER |= (1UL << 0);  /* CC1E */
    TIM4_CCR1 = 0;
    TIM4_CR1 = (1UL << 7) | (1UL << 0); /* ARPE, CEN */
}

int main(void)
{
    systick_init_1ms();
    gpio_pwm_init();
    pwm_timers_init();

    for (;;) {
        for (uint32_t duty = 0; duty <= PWM_STEPS - 1; duty++) {
            TIM3_CCR2 = duty;                 /* D9: brightening */
            TIM4_CCR1 = PWM_STEPS - 1 - duty;  /* D10: dimming */
            delay_ms(15);
        }
        for (uint32_t duty = PWM_STEPS - 1; duty > 0; duty--) {
            TIM3_CCR2 = duty;                 /* D9: dimming */
            TIM4_CCR1 = PWM_STEPS - 1 - duty;  /* D10: brightening */
            delay_ms(15);
        }
    }
}
